# Journey Planner Stack - Travel Planning Application
# Deploy AFTER Traefik stack
# Portainer Stack Name: journey-planner
# URL: https://malina.tail384b18.ts.net/journey

networks:
  web:
    external: true
  journey-planner-net:
    driver: bridge

volumes:
  attachment_uploads:
    driver: local

services:
  backend:
    image: ghcr.io/adasrakieta/journey-planner/backend:${IMAGE_TAG:-latest}
    container_name: journey-planner-api

    environment:
      - PORT=${BACKEND_PORT:-5001}
      - NODE_ENV=${NODE_ENV:-production}

      # Database Configuration
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-journey_planner}
      - DB_USER=${DB_USER:-journey_user}
      - DB_PASSWORD=${DB_PASSWORD}

      # JWT Authentication
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-1h}
      - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN:-7d}

      # Email Configuration (Gmail SMTP)
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_SECURE=${SMTP_SECURE:-false}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL:-${SMTP_USERNAME}}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME:-Journey Planner}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - EMAIL_PREVIEW_ENABLED=${EMAIL_PREVIEW_ENABLED:-1}

      # URLs for CORS and emails
      - FRONTEND_URL=${FRONTEND_URL}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - VITE_API_URL=${VITE_API_URL}

      # File Upload Configuration
      - UPLOAD_DIR=/app/uploads/attachments
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-10485760}
      - ALLOWED_FILE_TYPES=${ALLOWED_FILE_TYPES:-application/pdf,image/jpeg,image/png,image/jpg}

      # Exchange Rates API
      - EXCHANGERATE_API_KEY=${EXCHANGERATE_API_KEY}

      # Google OAuth
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}

      # File Encryption
      - FILE_ENCRYPTION_KEY=${FILE_ENCRYPTION_KEY}

    volumes:
      - attachment_uploads:/app/uploads/attachments

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    networks:
      - web
      - journey-planner-net

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      
      # Backend API → https://malina.tail384b18.ts.net/journey/api/*
      - "traefik.http.routers.journey-api.rule=Host(`malina.tail384b18.ts.net`) && PathPrefix(`/journey/api`)"
      - "traefik.http.routers.journey-api.entrypoints=web"
      - "traefik.http.routers.journey-api.priority=200"
      - "traefik.http.services.journey-api.loadbalancer.server.port=5001"
      
      # Middleware: strip /journey prefix (leaves /api)
      - "traefik.http.middlewares.journey-api-strip.stripprefix.prefixes=/journey"
      - "traefik.http.routers.journey-api.middlewares=journey-api-strip"

  frontend:
    image: ghcr.io/adasrakieta/journey-planner/frontend:${IMAGE_TAG:-latest}
    container_name: journey-planner-web

    environment:
      - VITE_API_URL=${VITE_API_URL}

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/index.html"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

    networks:
      - web
      - journey-planner-net

    depends_on:
      - backend

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      
      # Frontend → https://malina.tail384b18.ts.net/journey/*
      - "traefik.http.routers.journey-frontend.rule=Host(`malina.tail384b18.ts.net`) && PathPrefix(`/journey`)"
      - "traefik.http.routers.journey-frontend.entrypoints=web"
      - "traefik.http.routers.journey-frontend.priority=100"
      - "traefik.http.services.journey-frontend.loadbalancer.server.port=80"
      
      # Middleware: strip /journey prefix
      - "traefik.http.middlewares.journey-frontend-strip.stripprefix.prefixes=/journey"
      - "traefik.http.routers.journey-frontend.middlewares=journey-frontend-strip"
