version: '3.8'

networks:
  web:
    external: true

volumes:
  journey_attachment_uploads:
    driver: local

services:
  journey-planner-api:
    image: ghcr.io/adasrakieta/journey-planner/backend:${IMAGE_TAG:-latest}
    container_name: journey-planner-api
    environment:
      - PORT=5001
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=1h
      - JWT_REFRESH_EXPIRES_IN=7d
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_SECURE=${SMTP_SECURE:-false}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME:-Journey Planner}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - EMAIL_PREVIEW_ENABLED=1
      - FRONTEND_URL=${FRONTEND_URL}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - UPLOAD_DIR=/app/uploads/attachments
      - MAX_FILE_SIZE=10485760
      - ALLOWED_FILE_TYPES=${ALLOWED_FILE_TYPES}
      - FILE_ENCRYPTION_KEY=${FILE_ENCRYPTION_KEY}
      - EXCHANGERATE_API_KEY=${EXCHANGERATE_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
    volumes:
      - journey_attachment_uploads:/app/uploads/attachments
    networks:
      - web
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  journey-planner-web:
    image: ghcr.io/adasrakieta/journey-planner/frontend:${IMAGE_TAG:-latest}
    container_name: journey-planner-web
    environment:
      - VITE_API_URL=${VITE_API_URL}
    networks:
      - web
    depends_on:
      - journey-planner-api
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/index.html"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
